---
- name: Install tb-rest-client using pip3
  pip:
    name: tb-rest-client
    executable: pip3

- name: Create directories for ThingsBoard
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "~/.mytb-data"
    - "~/.mytb-logs"

- name: Set ownership for ~/.mytb-logs directory
  file:
    path: "{{ item }}"
    owner: "799"
    group: "799"
    recurse: yes
  loop:
    - "~/.mytb-data"
    - "~/.mytb-logs"

- name: Run the ThingsBoard Docker container, port open on {IP}:9090
  docker_container:
    name: mytb
    image: thingsboard/tb-postgres
    restart_policy: always
    ports:
      - "9090:9090"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    volumes:
      - "~/.mytb-data:/data"
      - "~/.mytb-logs:/var/log/thingsboard"

- name: Wait for the ThingsBoard container to start
  wait_for:
    host: localhost
    port: 9090
    delay: 10
    timeout: 60
    state: started

- name: change admin password
  command: "python3 ansible-thingsboard/script.py {{ admin_password }}"

